version: '3.0'
services:
  led:
    container_name: pystock
    build: .
    restart: on-failure
    image: xavbm/pystock
    volumes:
      - type: bind
        source: ./stockAndQuantity.py
        target: /usr/src/app/stockAndQuantity.py