apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-service
secrets:
  - name: dockercreds

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: xavbm-pystockdailyaverage-git
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/Xavbm/pyStockDailyAverage.git

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image-pystockdailyaverage
spec:
  type: image
  params:
    - name: url
      value: xavbm/pyStockTT