apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: led-api
  name: led-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: led-api
  template:
    metadata:
      labels:
        app: led-api
    spec:
      containers:
        - image: xavbm/pystock
          name: led
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: led-service
              servicePort: 5000